spring:
    profiles: local

spring:
datasource:
 mariadb:
         driver-class-name: org.mariadb.jdbc.Driver
         jdbc-url: jdbc:mariadb://localhost:3306/testing_local
         username: root
          password: root
         liquibase:
                        change-log: classpath:/db/changelog/db.changelog-master.yaml
   jpa:
       database: mysql
       show-sql: false
   liquibase:
     enabled: true
     drop-first: true
     contexts: test