spring:
  profiles: local

spring:
  datasource:
    name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3333/testing_local
    username: root
    password: root
    liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml